# app block
FROM node:lts-alpine as reactApp

WORKDIR /client
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build


# nginx block
FROM nginx:1.23.4-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=reactApp /app/build .
COPY nginx.conf /etc/nginx/
EXPOSE 3000
ENTRYPOINT ["nginx", "-g", "daemon off;"]