version: "3.9"

services:
  mysqldb:
    container_name: workout-db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_DB_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  backend:
    depends_on:
      - mysqldb
    build:
      context: ./backend
      dockerfile: Dockerfile_prod
    restart: always
    env_file:
      - ./.env
    ports:
      - "2000:2000"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQL_DB_USER
      - DB_PASSWORD=$MYSQL_DB_PASSWORD
      - DB_DATABASE=$MYSQL_DB_DATABASE
      - DB_PORT=$MYSQL_DB_DOCKER_PORT
    networks:
      - backend
      - frontend

  client:
    restart: always
    depends_on:
      - backend
    build:
      context: ./client
      dockerfile: Dockerfile_prod
    ports:
      - "3000:3000"
    networks:
      - frontend

volumes:
  db:

networks:
  backend:
  frontend: